[build]
# Specify the system packages required for cairo/cairosvg
packages = [
    "libcairo2-dev", 
    "libpq-dev"
]

# This comment change forces a new build
# **Cache Bust: v2** <--- Add or modify a comment here!